version: '3.8'
services:
  postgres-db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vertx-stock-broker
      - TZ=UTC
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
    driver: local